name: Deploy Production
on:
  workflow_dispatch:
  push:
    tags:
      - '*.*.*'

env:
  URL: 'docs.atsign.com'

permissions:  # added using https://github.com/step-security/secure-workflows
  contents: read

jobs:
  deploy:
    if: ${{ github.repository == 'atsign-foundation/docs.atsign.com' }}
    runs-on: ubuntu-20.04
    steps:
      - name: Git checkout
        uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f # v3.4.0

      - name: Setup Node
        uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3.6.0
        with:
          node-version: '16'

      - name: Cache dependencies
        uses: actions/cache@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8 # v3.3.1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm ci

      - name: Build Production
        run: npm run build:production

      - name: Deploy Production
        uses: peaceiris/actions-gh-pages@bd8c6b06eba6b3d25d72b7a1767993c0aeee42e7 # v3.9.2
        with:
          personal_token: ${{ secrets.MY_GITHUB_TOKEN }}
          external_repository: atsign-foundation/docs.atsign.com-prod
          publish_dir: ./public
          publish_branch: gh-pages
          cname: ${{ env.URL }}

